# Generated by Django 3.0.6 on 2020-05-24 08:28

import apps.food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(upload_to=apps.food.models.gallery_image_path)),
                ('type', models.SmallIntegerField(choices=[(0, '아침'), (1, '점심'), (2, '저녁')], default=0)),
            ],
            options={
                'db_table': 'food_gallery',
            },
        ),
    ]
