# Generated by Django 3.0.6 on 2020-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200524_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgallery',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
