# Generated by Django 3.0.6 on 2020-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodgallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgallery',
            name='type',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], default='아침', max_length=10),
        ),
    ]
