# Generated by Django 3.0.6 on 2020-06-03 09:59

import apps.food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_targetnutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.food.models.gallery_image_path)),
                ('type', models.IntegerField(choices=[(0, '적음'), (1, '보통'), (2, '많음')], default=1)),
            ],
        ),
    ]
